name: ci

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Step 2: Lint Dockerfile
      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./Dockerfile

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}

      # Step 4: Build and push (base stage)
      - name: Build and push (base stage)
        uses: docker/build-push-action@v6
        with:
          target: base
          cache-from: type=registry,ref=${{ vars.DOCKER_USER }}/redv2:cache
          cache-to: type=registry,ref=${{ vars.DOCKER_USER }}/redv2:cache,mode=max
          tags: ${{ vars.DOCKER_USER }}/redv2:base

      # Step 5: Build and push (build stage)
      - name: Build and push (build stage)
        uses: docker/build-push-action@v6
        with:
          target: build
          cache-from: type=registry,ref=${{ vars.DOCKER_USER }}/redv2:cache
          cache-to: type=registry,ref=${{ vars.DOCKER_USER }}/redv2:cache,mode=max
          tags: ${{ vars.DOCKER_USER }}/redv2:build

      # Step 6: Build and push (runtime stage)
      - name: Build and push (runtime stage)
        uses: docker/build-push-action@v6
        with:
          target: runtime
          cache-from: type=registry,ref=${{ vars.DOCKER_USER }}/redv2:cache
          cache-to: type=registry,ref=${{ vars.DOCKER_USER }}/redv2:cache,mode=max
          tags: ${{ vars.DOCKER_USER }}/redv2:latest

      # Step 7: Test Docker Image
      - name: Test Docker Image
        run: |
          docker run --rm ${{ vars.DOCKER_USER }}/redv2:latest python -c "import scikit_image"
          docker run --rm ${{ vars.DOCKER_USER }}/redv2:latest ls /workspace/VisoMaster
